config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = 'localhost:3000'
  root :to => 'home#index'

  devise_for :users, controllers: { registrations: 'user/registrations',  },
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :designers, :products
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    cart_ids = $redis.smembers current_user_cart
    @cart_products = Product.find(cart_ids)
  end

  def add
    $redis.sadd current_user_cart, params[:product_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:product_id]
    render json: current_user.cart_count, status: 200
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>My Cart</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> Items!</p>
  </div>

  <% @cart_products.each do |product|%>
      <div data-equalizer class="cart-movie large-12 column mb1">
        <div class="column large-2 text-center p0" data-equalizer-watch>
          <%=link_to product do%>
              <%=image_tag product.poster, class: "radius-l1"%>
          <%end%>
        </div>
        <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
          <p class="scale ptm"> <%= product.description %> </p>
        </div>
        <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
          <%=link_to "" , data: {targetUrl: remove_from_cart_path(product)} do%>
              <i class="fi-x right"></i>
          <%end%>
          <h4 class="scale">$ <%= product.price %></h4>
        </div>
      </div>
  <%end%>
</div>