config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = 'localhost:3000'
  root :to => 'home#index'

  devise_for :users, controllers: { registrations: 'user/registrations',  },
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :designers, :products
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end
end

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
    <div class="row">
      <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
    </div>
<%end%>

app/views/layouts/_header.html.erb
<div class="row">
  <nav class="top-bar column" data-topbar>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="menu-text"><%= link_to 'ZA Threads', root_path %></li>
          <% if signed_in? %>
              <li>
                <%= link_to cart_path do %>
                    <i class="fi-shopping-cart"></i>
                    My Cart
                    (<span class="cart-count"><%= current_user.cart_count %></span>)
                <% end %>
              </li>
              <li>
                <%= link_to current_user.name, edit_user_registration_path %>
              </li>
              <% if current_user.admin? %>
                  <li><%= link_to 'Manage Designers', designers_path %></li>
              <% end %>


              <% if current_user.is_designer and current_user.designer_approved? %>
                  <li> <%= link_to 'Edit Profile', edit_designer_path(current_user.id) %></li>
                  <li> <%= link_to 'Manage My Products', :controller => 'products', :action => 'index', :id => current_user.id %>
                  </li>
              <% end %>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %> </li>
          <% else %>
              <li><%= link_to 'Register', new_user_registration_path %></li>
              <li> <%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
      <ul class="menu">
        <div class="top-bar-right">
          <ul class="menu">
            <li><%= link_to 'Designers', designers_path %></li>
            <li><%= link_to 'Products', products_path %></li>
          </ul>
        </div>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "ZA Threads" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <%= render "layouts/header" %>

  <%= render "layouts/alerts" %>

  <div id="main-content" class="row full-min-height">
    <%= yield %>
  </div>

  <footer class="row">
    <div class="large-12 columns">
      <hr> <p>© ZA Threads 2016 by <a href="http://www.skpenterprise.co.za/">SKP Enterprise Solutions</a></p>
    </div>
  </footer>

  <%= javascript_include_tag "application" %>

  </body>
</html>